### ISSUE TITLE
lv_lib_bmp/v7 & lv_fs api

### ISSUE THREAD

**Issue by glory-man** [lvgl/lv_lib_bmp#2] opened 2021-12-01 15:56 UTC
Is bmp-library code compatible with lv_fs-v7 api.
I use lvgl-v7.6.1 (from zephyr-rtos repo) and I have lv_fs-function prototypes incompatible with used in library
For, example lv_fs_open - prototype in lvgl
```
lv_fs_res_t lv_fs_open(lv_fs_file_t * file_p, const char * path, lv_fs_mode_t mode)
```
which [called](https://github.com/lvgl/lv_lib_bmp/blob/359b97592722a0dd53f8f7d6a581f6a76d8e4222/lv_bmp.c#L88)
```
lv_fs_file_t * f;
f = lv_fs_open(src, LV_FS_MODE_RD);
```

**Comment by glory-man** [comment] 2021-12-01 15:59
In my app I use following file
[lv_bmp.c.txt](https://github.com/lvgl/lv_lib_bmp/files/7635364/lv_bmp.c.txt)

**Comment by kisvegabor** [comment] 2021-12-03 08:57
For v7 you can use this branch: https://github.com/lvgl/lv_lib_bmp/tree/release/v7

**Comment by glory-man** [comment] 2021-12-03 12:45
I copied this piece of code from lv_bmp.c located in the branch you linked to.
```
/*Save the data in the header*/
lv_fs_file_t * f;
f = lv_fs_open(src, LV_FS_MODE_RD);
if(f == NULL) return LV_RES_INV;
```

**Comment by glory-man** [comment] 2021-12-03 12:47
> For v7 you can use this branch: https://github.com/lvgl/lv_lib_bmp/tree/release/v7

I copied this piece of code from lv_bmp.c located in the branch you linked to 
```
/*Save the data in the header*/
lv_fs_file_t * f;
f = lv_fs_open(src, LV_FS_MODE_RD);
if(f == NULL) return LV_RES_INV;
```
link [here](https://github.com/lvgl/lv_lib_bmp/blob/359b97592722a0dd53f8f7d6a581f6a76d8e4222/lv_bmp.c#L87)

**Comment by kisvegabor** [comment] 2021-12-06 09:50
I see what the problem is. 

The BMP lib was compatible with the `feat/new-fs-api` branch of LVGL v7, but when v8 was released this branch was removed.  

From the README of the BMP lib:
> Compatible with LVGL's feat/new-fs-api branch. If you use the lv_fs_if repository it's new-api branch should be used.

Sorry for this incompatibility. :slightly_frowning_face: 

 As the BMP lib is quite simple it doesn't seem too complicated to refactor the FS API here to work with the "normal" LVGL v7 file system API.

For exampe for `lv_fs_open` [this](https://docs.lvgl.io/7.11/overview/file-system.html#_CPPv410lv_fs_openP12lv_fs_file_tPKc12lv_fs_mode_t) should used.

Can you give a try to refactor the API in this lib?

**Comment by glory-man** [comment] 2021-12-06 13:09
Forgot in [previously](https://github.com/lvgl/lv_lib_bmp/issues/2#issuecomment-983783669) attached file memory free for lv_fs_file_t object.
Here updated
[lv_bmp.c.txt](https://github.com/lvgl/lv_lib_bmp/files/7661321/lv_bmp.c.txt)
Now bmp-file content reads line-by-line and lv_fs_file_t should store in memory. If add read full content of bmp and put it to img_data (like it maded in lv_lib_png) decoder_read_line() may be removed.

**Comment by glory-man** [comment] 2021-12-21 14:38
new exp for me #3

**Comment by kisvegabor** [comment] 2021-12-22 17:02
I've merged the PR so this issue can be closed.

Thank you for the patch.

**Closed as completed** 2021-12-22 17:02 UTC
